### ISSUE TITLE
"Error connecting ('127.0.0.1', 9999)| Sleep 10 seconds"

### ISSUE THREAD

**Issue by RaaStaM4n** [MayankFawkes/Python-Botnet#2]
this really is a great project and the server is perfectly designed, the only problem is that when I try to connect the client I get the above error. Is this fixable?

**Comment by MayankFawkes** [comment]
Hello, error while connecting problem means the client unable to connect with port 9999 and it will retry connecting to same port after 10 seconds. This is because your didnt started the server file before started the client cause server has to be started or client cant be connected to server or you started server on different port.

And if you started Client first then Server then wait for 10 seconds it will automatically connect to server.
